// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiiConcatelPractice.Models;

namespace SiiConcatelPractice.Migrations
{
    [DbContext(typeof(RebelDbContext))]
    [Migration("20210324130143_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("SiiConcatelPractice.Models.Rebelde", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Planeta")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rebeldes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Fecha = new DateTime(2021, 3, 24, 14, 1, 43, 627, DateTimeKind.Local).AddTicks(4556),
                            Nombre = "Rebelde 1",
                            Planeta = "Marte"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
